"""NOVA Remote Protocol package."""

from nova.protocol.errors import ProtocolErrorCode, format_error_payload
from nova.protocol.models import (
    PROTOCOL_VERSION,
    SERVER_VERSION,
    AgentStatus,
    CapabilitiesMatrix,
    CapabilityInfo,
    DeviceInfo,
    DeviceRole,
    DeviceStatus,
    EmergencyActionRequest,
    EmergencyActionResponse,
    HealthResponse,
    PairingRequest,
    PairingResponse,
    RemoteQueryRequest,
    RemoteQueryResponse,
    ScreenCaptureRequest,
    ScreenCaptureResponse,
    SystemMetrics,
    SystemStatus,
    TaskCancelRequest,
    TaskCancelResponse,
    TaskRecord,
    TaskStatus,
    WebSocketEvent,
)

__all__ = [
    "PROTOCOL_VERSION",
    "SERVER_VERSION",
    "AgentStatus",
    "CapabilitiesMatrix",
    "CapabilityInfo",
    "DeviceInfo",
    "DeviceRole",
    "DeviceStatus",
    "EmergencyActionRequest",
    "EmergencyActionResponse",
    "HealthResponse",
    "PairingRequest",
    "PairingResponse",
    "ProtocolErrorCode",
    "RemoteQueryRequest",
    "RemoteQueryResponse",
    "ScreenCaptureRequest",
    "ScreenCaptureResponse",
    "SystemMetrics",
    "SystemStatus",
    "TaskCancelRequest",
    "TaskCancelResponse",
    "TaskRecord",
    "TaskStatus",
    "WebSocketEvent",
    "format_error_payload",
]
